### ISSUE TITLE
Hub connection request timed out

### ISSUE THREAD

**Issue by ilyes495** [AxeldeRomblay/MLBox#29]
I tried to run the code in the picture below, but I got the error saying TimeoutError: Hub connection request timed out.
I'm using Python2.7 under Ubuntu 16.04

![hub connection time out](https://user-images.githubusercontent.com/17175391/28815424-06f7c41a-76aa-11e7-92fe-dac481293aea.png)

Thanks for your help

**Comment by AxeldeRomblay** [comment]
Hi, 
Actually if you import mlbox.preprocessing, you have to wait approx 30 sec so that engines are ready... You can check in terminal that the following message appears : 'the engines appear to have started successfully'

Here is the doc for ipyparallel: https://ipyparallel.readthedocs.io/en/latest/process.html

At the moment, you have to kill your kernel or shutdown your VM, restart your code and wait 30 sec before running `fit_transform`

**Comment by maskani-moh** [comment]
@AxeldeRomblay 

What about warning the user when instanciating a `Drift_thresholder`. (Do a print basically asking to wait) ?

**Comment by ilyes495** [comment]
I restarted the kernel, run the imports and waited for more than 30 sec, when I ran the code, I got the same error

**Comment by ilyes495** [comment]
@maskani-moh I don't get a warning when instantiating  drift_thrsholder

**Comment by maskani-moh** [comment]
@ilyes495 

I know that. What I was suggesting to the developers is to put a warning to let the user wait 30s, which is not the case right now.

**Comment by AxeldeRomblay** [comment]
@ilyes495. Did you get the warning when importing the lib ? What you can do: `os.system("ipcluster stop --profile=home &")` and then restart: `os.system("ipcluster start --profile=home &")` and then wait for the engines to be ready, etc... . Otherwise restart your computer ??? 

Anyway, we will get rid of ipyparallel for next releases as it is too complicated to use (it is helpful if you want to distribute on several machines...)

**Comment by ilyes495** [comment]
I ran these commands and the problem was solved. 
    jupyter serverextension enable --py ipyparallel
    jupyter nbextension install --py ipyparallel
    jupyter nbextension enable --py ipyparallel

**Comment by ilyes495** [comment]
I got an error after that on preprocessing file line 148 "fichier.write(var + " = " + str(d) + '\n')"  
saying: TypeError: unsupported operand type(s) for +: 'int' and 'str', could be that var is an int rather than a string?

**Comment by ilyes495** [comment]
I solved the previous problem, by adding str(var).

**Comment by AxeldeRomblay** [comment]
thanks for reporting this issue :)
