### ISSUE TITLE
Code implementation frozen

### ISSUE THREAD

**Issue by yousseferahim** [AxeldeRomblay/MLBox#30]
Hello,

I tried implementing  the code in  https://www.analyticsvidhya.com/blog/2017/07/mlbox-library-automated-machine-learning/.
The engines start but the code implementation is frozen (still running but no task is done). I get the following message on my screen:

![screen](https://user-images.githubusercontent.com/23098804/28823425-c3f07b4e-76bd-11e7-8d3e-6e325b198f49.jpg)

I tried to put time.sleep but it doesn't change.
I'm on Windows 10 Pro, Python 3.5 with Anaconda
Do you have any idea why?

**Comment by AxeldeRomblay** [comment]
Hello,

Do you run the code with Jupyter ? Can you give me a screenshot of your code please ?

**Comment by yousseferahim** [comment]
No, I ran it first from PyCharm (IDE based on Anaconda) then directly from Windows command.

![code](https://user-images.githubusercontent.com/23098804/28836933-49772178-76eb-11e7-8a64-78833dd08b3f.jpg)

**Comment by AxeldeRomblay** [comment]
Here is the mistake (from the blog actually), you forgot to put "__" instead of "_" when optimising the parameters. 

For example: space = {'ne__numerical_strategy':{"search":"choice","space":['mean','median']}}
instead of : space = {'ne_numerical_strategy':{"search":"choice","space":['mean','median']}}

I have warned the author of the blog about this mistake... 
Thanks for the issue !

**Comment by yousseferahim** [comment]
Despite this parsing mistake, the problem persists with the same message as above.

**Comment by AxeldeRomblay** [comment]
did you install from the github or from pip ? try to install it from pip and run again your code please... otherwise you can try on another IDE like jupyter, it would work I hope !

**Comment by SethKitchen** [comment]
I have the same issue.

**Comment by SethKitchen** [comment]
Was solved by running in jupyter notebook
