### ISSUE TITLE
Drift meaning

### ISSUE THREAD

**Issue by ilyes495** [AxeldeRomblay/MLBox#33]
in the documentation,it says that a drift coefficient of 0.5 is very stable and a coefficient of 1 is not, so when we have two values, let's say 0.5 and 0.57 which one is the most stable?  according to the documentation is 0.5, but I when I ran it on my dataset I got the one with 0.57 as the top coefficient.

Please if someone can explain me the concept and how I should interpret the results.

Thanks

**Comment by AxeldeRomblay** [comment]
Yes so 0.5 is the most stable feature you can get and 1. the worst. In your case, 0,57 > 0.5 so the one with 0.57 is less stable than the one if 0.5 but it still remains a stable feature since 0.57 << 1.

We can assume that features with:

-  drift coeff < 0.6 are stable
- between 0.7 and 0.8 not stable
- >0.9 you have to delete it !!

**Comment by ilyes495** [comment]
thank you for your reply.
so maybe you have to reverse sort the list, because I got the highest drift coefficient (0.6) at the top and the lowest (0.5) at the bottom

**Comment by AxeldeRomblay** [comment]
I have updated the code: now the drift measure is normalized between 0. and 1. 

- 0. of drift (ie 0%)= the most stable feature you can get 
- 1. (ie 100%) = the most unstable feature you can get
